name: my_accrypt
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1



###########################################################################
# flutter pub run build_runner build --delete-conflicting-outputs
###########################################################################

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # state management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  #freezed
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  analyzer: ^6.7.0

  # local
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

  # network
  dio: ^5.7.0

  # UI
  flutter_sliding_toast: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true